"""
Генерирует nginx map-файл для коротких редиректов /go/litres/<slug>/
из lab_site/src/data/books.json.

Выход: affiliate_links/nginx/affiliate_map.conf (для include в nginx server)
      + для каждой книги — статический /go/litres/<slug>/ → 302 на партнёрский URL.

Подключение в nginx (sites-available/lab-site):
    http {
        map $aff_slug $aff_litres_path {
            default "";
            include /var/www/lab-site/affiliate_map.conf;  # generated
        }
        map $aff_slug $aff_litres_query {
            default "";
            include /var/www/lab-site/affiliate_map_query.conf;
        }
        server {
            ...
            location = /go/litres/ { return 302 /library/; }
            location ~ "^/go/litres/([^/]+)/?$" {
                set $aff_slug $1;
                return 302 "https://www.litres.ru$aff_litres_path/$aff_litres_query";
            }
        }
    }

Запуск:
    python affiliate_links/build_nginx_map.py
    python affiliate_links/build_nginx_map.py --out-dir ./nginx
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_HERE = Path(__file__).parent
sys.path.insert(0, str(_HERE.parent))

from affiliate_links.advcake import build_litres_url, make_book_affiliate


BOOKS_JSON = (
    _HERE.parent / "lab_site" / "src" / "data" / "books.json"
)


def _format_query(qs: str) -> str:
    """?a=1&b=2 → a=1&b=2 (без ?)"""
    return qs.lstrip("?")


def build_paths(books: list[dict]) -> tuple[str, str]:
    """Сгенерировать содержимое nginx map-файлов.

    Returns: (paths_conf, queries_conf).
    """
    path_lines = ["# AUTO-GENERATED by affiliate_links/build_nginx_map.py",
                  "# Не редактируй руками — пересобирай через скрипт.",
                  "default \"\";"]
    query_lines = ["# AUTO-GENERATED by affiliate_links/build_nginx_map.py",
                   "# Не редактируй руками — пересобирай через скрипт.",
                   "default \"\";"]

    count = 0
    for book in books:
        aff = book.get("affiliate")
        if not aff:
            continue
        url = aff.get("advcake_url")
        if not url:
            continue
        # Парсим обратно в path + query
        # https://www.litres.ru/book/.../122351/?a=1&b=2
        from urllib.parse import urlparse, parse_qsl, urlencode
        parsed = urlparse(url)
        path = parsed.path  # /book/.../122351/
        query = urlencode(dict(parse_qsl(parsed.query)))  # a=1&b=2
        slug = book["slug"]
        path_lines.append(f'    "{slug}" "{path}";')
        query_lines.append(f'    "{slug}" "?{query}";')
        count += 1

    return "\n".join(path_lines) + "\n", "\n".join(query_lines) + "\n", count


def main() -> int:
    p = argparse.ArgumentParser(description="Генерация nginx map для /go/litres/")
    p.add_argument("--out-dir", default=str(_HERE / "nginx"),
                   help="куда писать *.conf (по умолчанию affiliate_links/nginx/)")
    args = p.parse_args()

    books = json.loads(BOOKS_JSON.read_text(encoding="utf-8"))["books"]
    paths_conf, queries_conf, count = build_paths(books)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    (out_dir / "affiliate_map.conf").write_text(paths_conf, encoding="utf-8")
    (out_dir / "affiliate_map_query.conf").write_text(queries_conf, encoding="utf-8")

    print(f"✅ Найдено {count} книг с affiliate → {out_dir}/", file=sys.stderr)
    print(f"   Подключи в nginx http {{}}:", file=sys.stderr)
    print(f"     map $aff_slug $aff_litres_path      {{ include {out_dir}/affiliate_map.conf; }}", file=sys.stderr)
    print(f"     map $aff_slug $aff_litres_query     {{ include {out_dir}/affiliate_map_query.conf; }}", file=sys.stderr)
    print(f"   server {{ location ~ '^/go/litres/([^/]+)/?$' {{", file=sys.stderr)
    print(f"     set $aff_slug $1;", file=sys.stderr)
    print(f"     return 302 \"https://www.litres.ru$aff_litres_path$aff_litres_query\";", file=sys.stderr)
    print(f"   }} }}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())